In [4]:
import numpy as np

y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [9]:
def mae(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true, y_predicted):
        # print(yt,yp)
        total_error+=abs(yt-yp)
    mae=total_error/len(y_true)    
    # print("Total error:",total_error)  
    return mae      

In [10]:
mae(y_true,y_predicted)

np.float64(0.5)

In [14]:
y_predicted-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [17]:
abserror=np.abs(y_predicted-y_true)

In [18]:
np.mean(abserror)

np.float64(0.5)

In [19]:
eplison=1e-15

In [20]:
y_predicted

array([1, 1, 0, 0, 1])

In [25]:
y_predicted_new = [max(i,eplison) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [27]:
y_predicted_new2 = [min(i,1-eplison) for i in y_predicted_new]
y_predicted_new2

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [28]:
y_predicted_new3=np.array(y_predicted_new2)
np.log(y_predicted_new3)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
-np.mean(y_true*np.log(y_predicted_new3)+(1-y_true)*np.log(1-y_predicted_new3))

In [ ]:
def log_log(y_true,y_predicted):
    eplison=1e-15
    y_predicted_new=[max(i,eplison) for i in y_predicted]
    y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [ ]:
log_log(y_true,y_predicted)

np.float64(17.2696280766844)

: 