In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


2025-02-19 08:01:53.306287: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-19 08:01:53.609936: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-02-19 08:01:53.862804: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1739952114.142448   30247 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739952114.192603   30247 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-19 08:01:54.695378: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

https://github.com/codebasics/deep-learning-keras-tf-tutorial/blob/master/22_word_embedding/supervised_word_embeddings.ipynb

In [2]:
reviews=['nice food',
         'amazing restaurant',
         'too good',
         'just loved it',
         'will go again',
         'horrible food',
         'never go there',
         'poor service',
          'poor quality',
          'need imporvement']
    
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",500)

[61, 185]

In [4]:
vocab_size=50
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)


[[23, 40], [14, 22], [35, 20], [37, 6, 46], [27, 19, 2], [29, 40], [21, 19, 19], [27, 2], [27, 2], [38, 25]]


In [5]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[23 40  0]
 [14 22  0]
 [35 20  0]
 [37  6 46]
 [27 19  2]
 [29 40  0]
 [21 19 19]
 [27  2  0]
 [27  2  0]
 [38 25  0]]


In [6]:
embeded_vector_size=5

In [7]:
model=Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

/workspaces/keras-exercise/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
X=padded_reviews
y=sentiment

In [9]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

2025-02-19 08:02:03.303808: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.fit(X,y,epochs=50,verbose=0)

In [11]:
loss, accuracy=model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - accuracy: 1.0000 - loss: 0.6155


1.0

In [12]:
weights=model.get_layer('embedding').get_weights()[0]
weights

array([[-0.05003158, -0.01737197, -0.03031299,  0.0081967 ,  0.02060629],
       [-0.03797647,  0.00948907,  0.0427465 ,  0.02690084, -0.02931634],
       [ 0.07531942,  0.0598223 ,  0.05175987,  0.00635828, -0.11105137],
       [-0.04092752, -0.01544689, -0.00562739, -0.02158276, -0.00384442],
       [-0.00716941, -0.02828415, -0.00098965, -0.03599247, -0.048956  ],
       [-0.02716169, -0.01258202, -0.01705146, -0.02403667,  0.02204956],
       [-0.03460231, -0.02184718, -0.02892784, -0.07101046,  0.03700886],
       [-0.02964141,  0.03767545,  0.04772966,  0.02362038,  0.03582178],
       [ 0.01099309, -0.04484179,  0.00792954,  0.00789192,  0.03234233],
       [ 0.04694739, -0.02594122, -0.01875185, -0.00539271, -0.00315803],
       [-0.00716911,  0.04683744, -0.01997458, -0.03291408,  0.02623084],
       [-0.04888376, -0.01333563, -0.00482555, -0.01280195,  0.01747878],
       [-0.03434112, -0.01434273,  0.03314784, -0.01059492,  0.03847399],
       [ 0.02838831, -0.03998798,  0.0

In [13]:
len(weights)

50