In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib  inline


2025-03-14 08:23:24.645444: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-14 08:23:24.887855: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-14 08:23:25.113281: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1741940605.297514   25849 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741940605.351882   25849 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-14 08:23:26.147576: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [2]:
df=pd.read_csv("insurance_data.csv")

In [3]:
df.head(10)

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1
5   56              1                 1
6   55              0                 0
7   60              0                 1
8   62              1                 1
9   61              1                 1

In [4]:
df.shape

(28, 3)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [6]:
len(X_train)

22

In [7]:
# scale can help model do better
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [8]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [9]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']
              )
model.fit(X_train_scaled,y_train,epochs=1000)

Epoch 1/1000


/workspaces/keras-exercise/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-03-14 08:23:34.559831: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 961ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - lo

In [10]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.6667 - loss: 0.5855


[0.5854937434196472, 0.6666666865348816]

In [11]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [12]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[0.6447141 ],
       [0.56694895],
       [0.40433905],
       [0.5943529 ],
       [0.6498545 ],
       [0.6799389 ]], dtype=float32)

In [13]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [14]:
# get weight from model
coef, intercept=model.get_weights()
coef, intercept

(array([[1.1257617 ],
        [0.74689245]], dtype=float32),
 array([-0.68011606], dtype=float32))

In [15]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [16]:
def prediction_function(age, affordibility):
    weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)
    

In [17]:
prediction_function(0.47,1)

/tmp/ipykernel_25849/574919516.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.6447141680486285

In [18]:
prediction_function(.18,1)

/tmp/ipykernel_25849/574919516.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.566948921977084

In [19]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon)for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon)for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [20]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [21]:
def gradient_decent(age, affordability, y_true, epochs,loss_thresold):
    # try to find w1, w2, bias   
    w1=w2=1
    bias=0 
    rate=0.5
    n=len(age)
    
    for i in range(epochs):
        weighted_sum=w1*age+w2*affordability+bias
        y_predicted=sigmoid_numpy(weighted_sum)
        
        loss=log_loss(y_true,y_predicted)
        
        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
        bias_d=np.mean(y_predicted-y_true)
        
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        
        print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
        if loss<=loss_thresold:
            break
    
    return w1,w2,bias    
        

In [22]:
class myNN:
    def __init__(self):
        self.w1=1
        self.w2=1
        self.bias=0
    def fit(self,X,y,epochs,loss_thresold):
        self.w1,self.w2,self.bias=self.gradient_decent(X['age'],X['affordibility'],y,epochs,loss_thresold)
    def predict(self,X_test):     
        weighted_sum=self.w1*X_test['age']+self.w2*X_test['affordibility']+self.bias
        return sigmoid_numpy(weighted_sum)
    
    def gradient_decent(self,age, affordability, y_true, epochs,loss_thresold):
    # try to find w1, w2, bias   
        w1=w2=1
        bias=0 
        rate=0.5
        n=len(age)
    
        for i in range(epochs):
            weighted_sum=w1*age+w2*affordability+bias
            y_predicted=sigmoid_numpy(weighted_sum)

            loss=log_loss(y_true,y_predicted)

            w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
            w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
            bias_d=np.mean(y_predicted-y_true)

            w1=w1-rate*w1d
            w2=w2-rate*w2d
            if i%50==0:
                print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            if loss<=loss_thresold:
                break
    
        return w1,w2,bias      

In [23]:
gradient_decent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000,0.6007)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:0, loss:0.7113403233723417
Epoch:1, w1:0.951309050414721, w2:0.8998384766138976, bias:0, loss:0.7049437880152859
Epoch:2, w1:0.9291619684235712, w2:0.8543880770572044, bias:0, loss:0.6993052593238982
Epoch:3, w1:0.9084179079556838, w2:0.8118995045564921, bias:0, loss:0.6943576384281475
Epoch:4, w1:0.8890233255496454, w2:0.7722634615046652, bias:0, loss:0.6900349522584057
Epoch:5, w1:0.870920747167955, w2:0.7353613402471417, bias:0, loss:0.6862734824669942
Epoch:6, w1:0.854049860257641, w2:0.7010676910254683, bias:0, loss:0.6830126499196405
Epoch:7, w1:0.8383485325252197, w2:0.6692525213982417, bias:0, loss:0.6801956585346196
Epoch:8, w1:0.8237537349858943, w2:0.6397833777872467, bias:0, loss:0.6777699161231555
Epoch:9, w1:0.8102023557195147, w2:0.6125271797757017, bias:0, loss:0.6756872590878301
Epoch:10, w1:0.7976318984134669, w2:0.5873517948751835, bias:0, loss:0.6739040127414273
Epoch:11, w1:0.7859810659328945, w2:0.564127355

(0.5738399872440308, 0.34449479487147006, 0)

In [24]:
coef, intercept

(array([[1.1257617 ],
        [0.74689245]], dtype=float32),
 array([-0.68011606], dtype=float32))

In [25]:
customModel=myNN()
customModel.fit(X_train_scaled,y_train,epochs=10000,loss_thresold=0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:0, loss:0.7113403233723417
Epoch:50, w1:0.6453809016695304, w2:0.3205351301256622, bias:0, loss:0.6640132539238187
Epoch:100, w1:0.6212936314060924, w2:0.32238790873678597, bias:0, loss:0.6639846026679034
Epoch:150, w1:0.6069437504577972, w2:0.3290028546302259, bias:0, loss:0.6639743994218038
Epoch:200, w1:0.5969419585591431, w2:0.33368165457667215, bias:0, loss:0.663969416924462
Epoch:250, w1:0.5899542869322209, w2:0.33695174739332934, bias:0, loss:0.6639669845868806
Epoch:300, w1:0.5850728110988508, w2:0.3392364772069628, bias:0, loss:0.6639657974918586
Epoch:350, w1:0.581662971638289, w2:0.3408325615553289, bias:0, loss:0.6639652182396915
Epoch:400, w1:0.5792812459980179, w2:0.3419474727557813, bias:0, loss:0.6639649356249332
Epoch:450, w1:0.5776177100604406, w2:0.3427262250268181, bias:0, loss:0.6639647977504753
Epoch:500, w1:0.5764558319132966, w2:0.3432701521315076, bias:0, loss:0.6639647304921202
Epoch:550, w1:0.575644346

In [26]:
customModel.predict(X_test_scaled)

2     0.648898
10    0.610118
21    0.537226
11    0.623677
14    0.651508
9     0.666973
dtype: float64

In [27]:
customModel.predict(X_test_scaled)

2     0.648898
10    0.610118
21    0.537226
11    0.623677
14    0.651508
9     0.666973
dtype: float64

In [28]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[0.6447141 ],
       [0.56694895],
       [0.40433905],
       [0.5943529 ],
       [0.6498545 ],
       [0.6799389 ]], dtype=float32)

In [30]:
import tensorflow_model_optimization as tfmot
quantize_model=tfmot.quantization.keras.quantize_model
q_aware_model=quantize_model(model)
q_aware_model.compile(optimizer='adam',
                      loss='sparse_categorical_crossentropy',
                      metrics=['accuracy']
                      )
q_aware_model.summary()

ValueError: `to_quantize` can only either be a keras Sequential or Functional model.

In [ ]:
converter=tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations=[tf.lite.Optimize.DEFAULT]
tflite_qaware_model=converter.convert()